// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQIskmlq9E2pQxJoLeNSIxd5rk9kEiOM',
    appId: '1:28542894497:web:b1953211ea568ec35d8be0',
    messagingSenderId: '28542894497',
    projectId: 'gmail-api-401916',
    authDomain: 'api-401916.firebaseapp.com',
    storageBucket: 'gmail-api-401916.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6tZcoIPzzJK_zocT4MOtTx_gMT-Py7Q',
    appId: '1:28542894497:android:8524f6430a5dd14d5d8be0',
    messagingSenderId: '28542894497',
    projectId: 'gmail-api-401916',
    storageBucket: 'gmail-api-401916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDytOTpgh6_93k76K8PA5ieeMoJSaobjxM',
    appId: '1:28542894497:ios:6c76b8d138a9fbbb5d8be0',
    messagingSenderId: '28542894497',
    projectId: 'gmail-api-401916',
    storageBucket: 'gmail-api-401916.appspot.com',
    iosBundleId: 'com.example.simpleSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDytOTpgh6_93k76K8PA5ieeMoJSaobjxM',
    appId: '1:28542894497:ios:6c76b8d138a9fbbb5d8be0',
    messagingSenderId: '28542894497',
    projectId: 'gmail-api-401916',
    storageBucket: 'gmail-api-401916.appspot.com',
    iosBundleId: 'com.example.simpleSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFQIskmlq9E2pQxJoLeNSIxd5rk9kEiOM',
    appId: '1:28542894497:web:f1768bea495492245d8be0',
    messagingSenderId: '28542894497',
    projectId: 'gmail-api-401916',
    authDomain: 'api-401916.firebaseapp.com',
    storageBucket: 'gmail-api-401916.appspot.com',
  );
}
